#file: noinspection SpellCheckingInspection
file-manager:
  type: "s3"
  endpoint: "https://s3.inkorcloud.top"
  bucket: "imlist"
  accessId: "FOebTaMCJ67ypGm5stQS"
  accessKey: "S7LJdKkM1VjxdMbQNoZ0TXlwSzeYSre1Lw1uVsSC"
  expire: 1800
  readPreSign: true

mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ""
    url: "jdbc:postgresql://localhost:5432/im_lite?TimeZone=Asia/Shanghai"
  mail:
    host: smtp.yeah.net
    protocol: smtp
    default-encoding: UTF-8
    from: inkorcloud_233@yeah.net
    username: inkorcloud_233@yeah.net
    password: MX3S47NQfHyNGCgn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    default-property-inclusion: non_null
login:
  expire: 604800
logging: